updated idam configuration
hmcts/adoption-cos-api pull request #141
Opened 2022-03-03 09:48 UTC by abidfs

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/ADOP-535

### Change description ###
updated idam configuration

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

2022-03-03 10:23 UTC, pankajhmcts approved these changes

2022-03-03 10:24 UTC, gauravtomar-gh submitted a review, later dismissed

2022-03-03 10:35 UTC, dilipsamrahmcts submitted a review, later dismissed

2022-03-04 09:35 UTC, rajatkgupta29 approved these changes

2022-03-28 13:47 UTC, pankajhmcts requested changes
On hold

2022-05-17 14:03 UTC, closed without merging