implemented changes for ADOP-817
hmcts/adoption-cos-api pull request #232
Opened 2022-04-25 16:59 UTC by praneethhm

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/ADOP-817

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
```

2022-04-26 14:13 UTC, abidfs commented
@praneethhm closing this one, please re-open it tomorrow
we are having issues with preview env pod limits

2022-04-27 14:35 UTC, sathishkannan-hmcts requested changes

2022-04-28 21:17 UTC, gauravtomar-gh commented
@rajatkgupta29, This is going to PROD, please review.

2022-04-29 14:12 UTC, rajatkgupta29 requested changes

2022-04-29 14:12 UTC, rajatkgupta29 commented on config/owasp/suppressions.xml
> +  <!--
Remove the commented code

2022-04-29 14:12 UTC, rajatkgupta29 commented on src/main/java/uk/gov/hmcts/reform/adoption/Application.java
>          DocumentManagementClient.class,
Yes

2022-07-21 23:03 UTC, closed without merging