Adop 979
hmcts/adoption-cos-api pull request #346
Opened 2022-07-13 18:09 UTC by mohitvijay45

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-07-14 04:12 UTC, pankajhmcts commented on src/main/java/uk/gov/hmcts/reform/adoption/common/service/task/SendSubmissionNotifications.java
>      // @Autowired
Remove commented code @mohitvijay45

2022-07-14 04:13 UTC, pankajhmcts commented on src/main/java/uk/gov/hmcts/reform/adoption/common/service/task/SendSubmissionNotifications.java
>          //log.info("Sending outstanding action notification if awaiting documents for case : {}", caseId);
Remove commented code or add log statements.

2022-07-14 04:13 UTC, pankajhmcts commented on src/test/java/uk/gov/hmcts/reform/adoption/notification/ApplicationSubmittedNotificationTest.java
> +//import static uk.gov.hmcts.reform.adoption.notification.NotificationConstants.*;
Remove commented code

2022-07-22 13:35 UTC, rajatkgupta29 requested changes
Please revert items modified with respect to LOCAL_COURT. Check in overall application not only in YAML.

2022-07-24 15:10 UTC, mohitvijay45 commented on src/main/resources/application.yaml
> -            LOCAL_COURT_APPLICATION_SUBMITTED: '381cfc64-5016-4fe7-bd88-3ceeb163ce69'
Added the property as suggested.

2022-07-25 23:29 UTC, pankajhmcts approved these changes

2022-07-27 10:26 UTC, rajatkgupta29 approved these changes

2022-07-27 14:01 UTC, pankajhmcts approved these changes

2022-07-27 14:01 UTC, merged