Adop 524
hmcts/adoption-cos-api pull request #396
Opened 2022-08-31 15:22 UTC by mohitvijay45

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-08-31 17:20 UTC, pankajhmcts approved these changes

2022-09-06 12:13 UTC, rajatkgupta29 approved these changes

2022-09-06 12:15 UTC, rajatkgupta29 requested changes

2022-09-06 12:15 UTC, rajatkgupta29 commented on src/test/java/uk/gov/hmcts/reform/adoption/caseworker/event/CaseworkerAddNoteTest.java
> +
Please enable the tests

2022-09-12 13:06 UTC, rajatkgupta29 approved these changes

2022-09-12 13:17 UTC, merged